### ISSUE TITLE
Doesn't build on debian

### ISSUE THREAD

**Issue by GarethNelson** [opencog/cogutils#2]
gareth@sexy:~/cogutils/trunk/build$ make
[  5%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/Config.cc.o
In file included from /home/gareth/cogutils/trunk/opencog/util/Config.cc:50:0:
/home/gareth/cogutils/trunk/opencog/util/exceptions.h:71:13: error: looser throw specifier for ‘virtual opencog::StandardException::~StandardException()’
In file included from /usr/include/c++/4.7/new:42:0,
                 from /usr/include/c++/4.7/ext/new_allocator.h:34,
                 from /usr/include/c++/4.7/x86_64-linux-gnu/bits/c++allocator.h:34,
                 from /usr/include/c++/4.7/bits/allocator.h:48,
                 from /usr/include/c++/4.7/string:43,
                 from /home/gareth/cogutils/trunk/opencog/util/Config.h:28,
                 from /home/gareth/cogutils/trunk/opencog/util/Config.cc:25:
/usr/include/c++/4.7/exception:66:13: error:   overriding ‘virtual std::exception::~exception() noexcept (true)’
make[2]: *** [opencog/util/CMakeFiles/cogutil.dir/Config.cc.o] Error 1
make[1]: *** [opencog/util/CMakeFiles/cogutil.dir/all] Error 2
make: *** [all] Error 2

gareth@sexy:~/cogutils/trunk/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by linas** [comment]
I just pushed a possible fox for this; can you try again?

**Comment by GarethNelson** [comment]
No luck :(

/home/gareth/cogutils/trunk/opencog/util/exceptions.cc:99:39: error: declaration of ‘virtual opencog::StandardException::~StandardException()’ has a different exception specifier
In file included from /home/gareth/cogutils/trunk/opencog/util/exceptions.cc:26:0:
/home/gareth/cogutils/trunk/opencog/util/exceptions.h:71:13: error: from previous declaration ‘virtual opencog::StandardException::~StandardException() noexcept (true)’
make[2]: *** [opencog/util/CMakeFiles/cogutil.dir/exceptions.cc.o] Error 1
make[1]: *** [opencog/util/CMakeFiles/cogutil.dir/all] Error 2
make: *** [all] Error 2

**Comment by GarethNelson** [comment]
Note that it DOES build in jessie (probably due to newer gcc), but annoyingly atomspace doesn't build

**Comment by linas** [comment]
Doh.  I just pushed another fix, third times a charm?

Report the atomspace build bugs with the issue tracker there.

**Comment by GarethNelson** [comment]
Third time is indeed a charm, it's built now
