### ISSUE TITLE
CMake Error at embodiment/CMakeLists.txt:4 (OPENCOG_ADD_ATOM_TYPES):   Unknown CMake command "OPENCOG_ADD_ATOM_TYPES".

### ISSUE THREAD

**Issue by rollybob** [opencog/cogutils#77]
I get this error when using "cmake .." CMake Error at embodiment/CMakeLists.txt:4 (OPENCOG_ADD_ATOM_TYPES):
  Unknown CMake command "OPENCOG_ADD_ATOM_TYPES".
 This is preventing me from using the make command, when I try I get "make: *** No targets specified and no makefile found.  Stop." What am I doing wrong?
[CMakeLists.txt](https://github.com/opencog/cogutils/files/963093/CMakeLists.txt)

**Comment by ngeiswei** [comment]
Maybe you need to install cogutils and atomspace?

**Comment by ngeiswei** [comment]
Hmm, this macro is defined in `opencog/lib` as well, maybe it's a problem with cmake. Could you tell us your system specification (OS, gcc, cmake versions) and explain what you've done so far?

**Comment by ngeiswei** [comment]
The error message seems to come from the opencog repo given that `embodiment` is mentioned. What error message do you get from cogutils?

**Comment by rollybob** [comment]
That is the message i get when compiling cogutils... CMake Error at embodiment/CMakeLists.txt:4 (OPENCOG_ADD_ATOM_TYPES):
Unknown CMake command "OPENCOG_ADD_ATOM_TYPES".

**Comment by ngeiswei** [comment]
That's very strange, I really don't understand. Have you tried to use https://github.com/opencog/ocpkg ?

**Comment by rollybob** [comment]
What is it?

**Comment by linas** [comment]
there is no directory called embodiment in cogutils.  I'm guessing you've got a bunch of code all checked into the same directory, you';ve got scrambled eggs. Try again, this time, each repo in its own dir.

**Comment by rollybob** [comment]
Thats what I did... I dont see how this happened... Maybe I clicked and dragged a folder in by mistake? I'll try again. Sometimes the simplest explanation is the best one right?

**Comment by rollybob** [comment]
ok so final update, yes there was some mystery folder mixed in. Where did embodiment come from? Anyway after attempting to use cmake a second time it said "Some but not all boost libraries were found." After using ./bootstrap.sh --help and then include libraries=all and installing it agian it worked. So hooray for that. Thanks to linas and everyone else for helping.
